# site settings
title: Kartav Kesri
subtitle: Personal webpage
email_1: kartav.kesri@etu.sorbonne-universite.fr
email_2: kartavkesri@gmail.com 
description: Welcome to my webpage <br /> It's nice to meet you!!.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Campus Pierre et Marie Curie, Sorbonne Universit&eacute
city: 4 Pl. Jussieu, Paris 
state: Ile-de France
zip_code: 75005
country: France
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Kartav33
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kartav-kesri-622718219/
  Twitter: https://twitter.com/KartavK87350
  Facebook:
  Slack:
  YouTube: https://www.youtube.com/channel/UCId44qOm3wcqltkabQqeyTQ

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
